import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateProntuariosSchema1765210569855 implements MigrationInterface {
    name = 'UpdateProntuariosSchema1765210569855'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Esta migration foi simplificada para evitar erros de ordem
        // As tabelas já foram criadas corretamente pelas migrations anteriores
        console.log('⏭️  Pulando UpdateProntuariosSchema - schema já configurado pelas migrations anteriores');
        return;
        
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT IF EXISTS "password_resets_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP CONSTRAINT "pacientes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP CONSTRAINT "pix_transactions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP CONSTRAINT "prontuarios_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP CONSTRAINT "prontuarios_paciente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "pagamentos_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "pagamentos_paciente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "pagamentos_pacote_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "pagamentos_agenda_sessao_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pacotes" DROP CONSTRAINT "pacotes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP CONSTRAINT "paciente_arquivos_paciente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP CONSTRAINT "paciente_arquivos_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP CONSTRAINT "cadastro_links_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP CONSTRAINT "anamneses_paciente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" DROP CONSTRAINT "agenda_sessoes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" DROP CONSTRAINT "agenda_sessoes_paciente_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" DROP CONSTRAINT "agenda_sessoes_user_id_paciente_id_data_horario_key"`);
        await queryRunner.query(`CREATE TABLE "cadastro_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cadastro_link_id" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "dados" json NOT NULL, "paciente_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac78a1460bb8bb71a1a1eaf4db5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "pix_key"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "qr_code"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "qr_code_image"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "payer_name"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "payer_cpf"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "end_to_end_id"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "queixa_principal"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "historia_doenca_atual"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "historia_pregressa"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "exame_mental"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "hipotese_diagnostica"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "plano_terapeutico"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "nome_original"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "nome_arquivo"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP COLUMN "campos_habilitados"`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD "reset_token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "UQ_c6e3466f270c86c6edd43e1ac84" UNIQUE ("reset_token")`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD "reset_code" character varying(6) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."pix_transactions_type_enum" AS ENUM('CHARGE', 'SEND', 'REFUND')`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "type" "public"."pix_transactions_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "valor" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "chave" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "descricao" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "qrcode" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "qrcodeImage" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "devedor" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "favorecido" jsonb`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "paidAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "expiredAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "pacienteId" uuid`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "e2eId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "refundId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "efipayResponse" jsonb`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "avaliacao_demanda" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "encaminhamento" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "anexos" json`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "nome" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "chave" character varying(512)`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_reports_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pontos" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."pontos" IS 'Valores em centavos'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "nivel_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "used" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP CONSTRAINT "pix_transactions_txid_key"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "txid"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "txid" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD CONSTRAINT "UQ_b9a01cd6dbe595e986a6d432b9e" UNIQUE ("txid")`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."pix_transactions_status_enum" AS ENUM('PENDING', 'PAID', 'EXPIRED', 'CANCELLED', 'REFUNDED', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "status" "public"."pix_transactions_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "evolucao"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "evolucao" json`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "sessoes_total" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "status" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "tipo" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" SET DEFAULT 'info'`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "read" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP CONSTRAINT "cadastro_links_token_key"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD "token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD CONSTRAINT "UQ_ba9f5248ca85d3c2acde963cf0e" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD "nome" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP CONSTRAINT "anamneses_paciente_id_key"`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD "tipo" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP COLUMN "respostas"`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD "respostas" jsonb NOT NULL DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f7a2b11e29b1422a2622beab3" ON "users" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_683d01a08c4623e5332ce189de" ON "pix_transactions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0e83e602d0953d8b2311a058" ON "pix_transactions" ("pacienteId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9a9af1d2ac880975621dfa715" ON "pix_transactions" ("userId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b9a01cd6dbe595e986a6d432b9" ON "pix_transactions" ("txid") `);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD CONSTRAINT "UQ_b4758059d6e756470d6baf2e9d0" UNIQUE ("user_id", "paciente_id")`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "FK_f7a4c3bc48f24df007936d217be" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD CONSTRAINT "FK_820c376e8b4668448ccf3333971" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD CONSTRAINT "FK_89ffd1d526d8c11b945f20f5404" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD CONSTRAINT "FK_c86ced3af58b332eb77c124213c" FOREIGN KEY ("pacienteId") REFERENCES "pacientes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "FK_91bf526f578724999358ea740a5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "FK_942c8634a5c7be41947265f75b2" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "FK_45d3ccab25bd4746affd5e11ae1" FOREIGN KEY ("pacote_id") REFERENCES "pacotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "FK_b63c9b81268e738fec8df49b0b3" FOREIGN KEY ("agenda_sessao_id") REFERENCES "agenda_sessoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pacotes" ADD CONSTRAINT "FK_aedd911853a6565a33317958a4e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD CONSTRAINT "FK_ffe2b62db612b058179702930d7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cadastro_submissions" ADD CONSTRAINT "FK_13f1d94bcf7f94da9fb691de70b" FOREIGN KEY ("cadastro_link_id") REFERENCES "cadastro_links"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cadastro_submissions" ADD CONSTRAINT "FK_e794c62c887614080437a85d1c4" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD CONSTRAINT "FK_4e47d1bafab4c018cb40138107f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD CONSTRAINT "FK_6bd0ad0d88a97920d57a51ad1c5" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ADD CONSTRAINT "FK_2b7cf136fd84d8c510af6d3a418" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ADD CONSTRAINT "FK_556606025a0f873433c9be358dc" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" DROP CONSTRAINT "FK_556606025a0f873433c9be358dc"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" DROP CONSTRAINT "FK_2b7cf136fd84d8c510af6d3a418"`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP CONSTRAINT "FK_6bd0ad0d88a97920d57a51ad1c5"`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP CONSTRAINT "FK_4e47d1bafab4c018cb40138107f"`);
        await queryRunner.query(`ALTER TABLE "cadastro_submissions" DROP CONSTRAINT "FK_e794c62c887614080437a85d1c4"`);
        await queryRunner.query(`ALTER TABLE "cadastro_submissions" DROP CONSTRAINT "FK_13f1d94bcf7f94da9fb691de70b"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP CONSTRAINT "FK_ffe2b62db612b058179702930d7"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "pacotes" DROP CONSTRAINT "FK_aedd911853a6565a33317958a4e"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "FK_b63c9b81268e738fec8df49b0b3"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "FK_45d3ccab25bd4746affd5e11ae1"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "FK_942c8634a5c7be41947265f75b2"`);
        await queryRunner.query(`ALTER TABLE "pagamentos" DROP CONSTRAINT "FK_91bf526f578724999358ea740a5"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP CONSTRAINT "FK_c86ced3af58b332eb77c124213c"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP CONSTRAINT "FK_89ffd1d526d8c11b945f20f5404"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP CONSTRAINT "FK_820c376e8b4668448ccf3333971"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT "FK_f7a4c3bc48f24df007936d217be"`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP CONSTRAINT "UQ_b4758059d6e756470d6baf2e9d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9a01cd6dbe595e986a6d432b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9a9af1d2ac880975621dfa715"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0e83e602d0953d8b2311a058"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_683d01a08c4623e5332ce189de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f7a2b11e29b1422a2622beab3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ALTER COLUMN "value" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "anamneses" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP COLUMN "respostas"`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD "respostas" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD "tipo" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD CONSTRAINT "anamneses_paciente_id_key" UNIQUE ("paciente_id")`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD "nome" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP CONSTRAINT "UQ_ba9f5248ca85d3c2acde963cf0e"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD "token" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD CONSTRAINT "cadastro_links_token_key" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "read" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "tipo" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pacotes" ALTER COLUMN "sessoes_total" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "evolucao"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "evolucao" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "metadata" json`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."pix_transactions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "status" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP CONSTRAINT "UQ_b9a01cd6dbe595e986a6d432b9e"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "txid"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "txid" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD CONSTRAINT "pix_transactions_txid_key" UNIQUE ("txid")`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ALTER COLUMN "used" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_admin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "nivel_id" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."pontos" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "pontos" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "whatsapp_reports_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamneses" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "chave"`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "anexos"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "encaminhamento"`);
        await queryRunner.query(`ALTER TABLE "prontuarios" DROP COLUMN "avaliacao_demanda"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "efipayResponse"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "refundId"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "e2eId"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "pacienteId"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "expiredAt"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "paidAt"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "favorecido"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "devedor"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "qrcodeImage"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "qrcode"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "descricao"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "chave"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "valor"`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."pix_transactions_type_enum"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP COLUMN "reset_code"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT "UQ_c6e3466f270c86c6edd43e1ac84"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP COLUMN "reset_token"`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD "campos_habilitados" json`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "nome_arquivo" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD "nome_original" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "plano_terapeutico" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "hipotese_diagnostica" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "exame_mental" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "historia_pregressa" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "historia_doenca_atual" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "queixa_principal" text`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD "data" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "end_to_end_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "payer_cpf" character varying(14)`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "payer_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "qr_code_image" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "qr_code" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "pix_key" text`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "amount" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD "code" character varying(6) NOT NULL`);
        await queryRunner.query(`DROP TABLE "cadastro_submissions"`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ADD CONSTRAINT "agenda_sessoes_user_id_paciente_id_data_horario_key" UNIQUE ("user_id", "paciente_id", "data", "horario")`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ADD CONSTRAINT "agenda_sessoes_paciente_id_fkey" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agenda_sessoes" ADD CONSTRAINT "agenda_sessoes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anamneses" ADD CONSTRAINT "anamneses_paciente_id_fkey" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cadastro_links" ADD CONSTRAINT "cadastro_links_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD CONSTRAINT "paciente_arquivos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente_arquivos" ADD CONSTRAINT "paciente_arquivos_paciente_id_fkey" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pacotes" ADD CONSTRAINT "pacotes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "pagamentos_agenda_sessao_id_fkey" FOREIGN KEY ("agenda_sessao_id") REFERENCES "agenda_sessoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "pagamentos_pacote_id_fkey" FOREIGN KEY ("pacote_id") REFERENCES "pacotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "pagamentos_paciente_id_fkey" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagamentos" ADD CONSTRAINT "pagamentos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD CONSTRAINT "prontuarios_paciente_id_fkey" FOREIGN KEY ("paciente_id") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prontuarios" ADD CONSTRAINT "prontuarios_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pix_transactions" ADD CONSTRAINT "pix_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD CONSTRAINT "pacientes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "password_resets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
